const index = require('../index.js');

/*
Statistics:
  Kerri Seger   0000XSNJG0MQJHBF4QX1EFD6Y3  7 docs
  Conard Faraon 0XXXXSNJG0MQJHBF4QX1EFD6Y3  7 docs
  Lisa Kim      0XXXXSNJG0MQASDF4QX1EFD6Y3  6 docs
  Shima Abadi   123XXSNJG0MQASDF4QX1EFD6Y3  4 docs
  Keem Leesa    123XXSNJG0MQASDF4QFFFFD6Y3  8 docs

 */

function callback(err, response) {
  if (err) {
    console.log(err);
  } else {
    console.log('Response ', response);
  }
}

const items = [
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Conga',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 21.37382047121921,
      longitude: -109.9239326211374,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1394709793,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Gunshot Maybe',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 8000,
      latitude: 19.458841946577305,
      longitude: -112.5826240273874,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1493816993,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Squeak Ascending Shriek',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 27.240461771986347,
      longitude: -118.2955146523874,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1393816993,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Squelch',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 21.593280323417385,
      longitude: -123.03730859289931,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1392026713,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Unknown 13',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 8000,
      latitude: 30.269698300765437,
      longitude: -120.68623437414931,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1427207773,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Whup Ascending Shriek',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 8000,
      latitude: 15.74348878054948,
      longitude: -107.24676851430542,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1394115793,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Wookie',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 24.103832712055066,
      longitude: -92.64963900883936,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1392031993,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Feed',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Norfolk',
        state: 'VA',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Probe',
      sensorName: 'SonarTech',
      sampleRate: 18000,
      latitude: 33.645088,
      longitude: -64.234964,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1457868193,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Part Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Providence',
        state: 'Maine',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Probe',
      sensorName: 'SonarTech',
      sampleRate: 18000,
      latitude: 39.836641,
      longitude: -55.094339,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1457004193,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Part Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Atlanta',
        state: 'Georgia',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Satellite',
      sensorName: 'Tsukino',
      sampleRate: 4000,
      latitude: 31.188857,
      longitude: -71.682163,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1517509423,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Part Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Atlanta',
        state: 'Georgia',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Satellite',
      sensorName: 'Tsukino',
      sampleRate: 21000,
      latitude: 32.136476,
      longitude: -72.266717,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1517529106,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Dependency Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Miara',
        state: 'Florida',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 25000,
      latitude: 33.025174,
      longitude: -67.256952,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1397107406,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Dependency Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Miara',
        state: 'Florida',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Stick',
      sensorName: 'Northrup',
      sampleRate: 9000,
      latitude: 30.257095,
      longitude: -72.442499,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1386689006,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Dependency Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Norfolk',
        state: 'Virginia',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 1000,
      latitude: 35.755160,
      longitude: -64.307162,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1455146336,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Kim',
        firstName: 'Lisa',
      },
      callTypeName: 'Coreography',
      groundType: 'Atlas',
      studySite: {
        city: 'McMurdo',
        state: 'Antarctica',
        country: 'USA',
      },
      ocean: 'Southern Ocean',
      sensorType: 'Wired',
      sensorName: 'Bahn',
      sampleRate: 600,
      latitude: -60.460843,
      longitude: -0.602151,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1454146426,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Kim',
        firstName: 'Lisa',
      },
      callTypeName: 'Coreography',
      groundType: 'Atlas',
      studySite: {
        city: 'McMurdo',
        state: 'Antarctica',
        country: 'USA',
      },
      ocean: 'Southern Ocean',
      sensorType: 'Wired',
      sensorName: 'Bahn',
      sampleRate: 600,
      latitude: -58.179671,
      longitude: 51.716274,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1453046626,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Kim',
        firstName: 'Lisa',
      },
      callTypeName: 'Coreography',
      groundType: 'Atlas',
      studySite: {
        city: 'McMurdo',
        state: 'Antarctica',
        country: 'USA',
      },
      ocean: 'Southern Ocean',
      sensorType: 'Wired',
      sensorName: 'Bahn',
      sampleRate: 7000,
      latitude: -59.172671,
      longitude: 141.013149,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 145446636,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Kim',
        firstName: 'Lisa',
      },
      callTypeName: 'Hibernate',
      groundType: 'Atlas',
      studySite: {
        city: 'Alesund',
        state: '',
        country: 'Norway',
      },
      ocean: 'Arctic Ocean',
      sensorType: 'Wired',
      sensorName: 'Bahn',
      sampleRate: 10000,
      latitude: 71.173307,
      longitude: -12.864505,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1355146666,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: [],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Kim',
        firstName: 'Lisa',
      },
      callTypeName: 'Feed Point',
      groundType: 'Cold Ground',
      studySite: {
        city: 'Hoffland',
        state: '',
        country: 'Norway',
      },
      ocean: 'Arctic Ocean',
      sensorType: 'Wired',
      sensorName: 'Bahn',
      sampleRate: 8000,
      latitude: 80.871617,
      longitude: -132.531781,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1510287809,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Kim',
        firstName: 'Lisa',
      },
      callTypeName: 'Feed Point',
      groundType: 'Cold Ground',
      studySite: {
        city: 'Copenhagen',
        state: '',
        country: 'Denmark',
      },
      ocean: 'Arctic Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 12000,
      latitude: 82.852433,
      longitude: 13.718219,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1310287801,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Abadi',
        firstName: 'Shima',
      },
      callTypeName: 'Herd',
      groundType: 'Migrating Ground',
      studySite: {
        city: 'Antananarivo',
        province: 'Antananarivo Province',
        country: 'Madagascar',
      },
      ocean: 'Indian Ocean',
      sensorType: 'Tag',
      sensorName: 'Core',
      sampleRate: 18000,
      latitude: 3.819570,
      longitude: 69.752682,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1420287802,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Abadi',
        firstName: 'Shima',
      },
      callTypeName: 'Herd',
      groundType: 'Migrating Ground',
      studySite: {
        city: 'Kerala',
        country: 'India',
      },
      ocean: 'Indian Ocean',
      sensorType: 'Tag',
      sensorName: 'Core',
      sampleRate: 3000,
      latitude: 1.374764,
      longitude: 66.188233,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1220288806,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Abadi',
        firstName: 'Shima',
      },
      callTypeName: 'Herd',
      groundType: 'Migrating Ground',
      studySite: {
        city: 'Colombo',
        province: 'Western Province',
        country: 'Sri Lanka',
      },
      ocean: 'Indian Ocean',
      sensorType: 'Tag',
      sensorName: 'Core',
      sampleRate: 2000,
      latitude: -6.346461,
      longitude: 74.362061,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1330284806,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Abadi',
        firstName: 'Shima',
      },
      callTypeName: 'Herd',
      groundType: 'Migrating Ground',
      studySite: {
        city: 'Colombo',
        province: 'Western Province',
        country: 'Sri Lanka',
      },
      ocean: 'Indian Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 17000,
      latitude: -3.193761,
      longitude: 57.662842,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1437725706,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Friend',
      groundType: 'Social Ground',
      studySite: {
        city: 'Tokyo',
        country: 'Japan',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 4000,
      latitude: 28.811156,
      longitude: 162.170557,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1440344996,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Friend',
      groundType: 'Social Ground',
      studySite: {
        city: 'Seoul',
        country: 'South Korea',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 2000,
      latitude: 48.839540,
      longitude: 164.983057,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1445344896,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Separation Call',
      groundType: 'Volcanic Ground',
      studySite: {
        city: 'Waikiki',
        country: 'Hawaii',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 18000,
      latitude: 34.136708,
      longitude: -156.153452,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1446744336,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Fish Call',
      groundType: 'Baja Ground',
      studySite: {
        city: 'Tijuana',
        state: 'Baja California',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 28.469495,
      longitude: -129.947424,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1446886347,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Fish Call',
      groundType: 'Baja Ground',
      studySite: {
        city: 'San Diego',
        state: 'California',
        country: 'USA',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 37.996406,
      longitude: -139.365051,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1446843537,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Fish Call',
      groundType: 'Baja Ground',
      studySite: {
        city: 'San Diego',
        state: 'California',
        country: 'USA',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 37.509971,
      longitude: -152.197083,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1516843537,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Fish Call',
      groundType: 'Baja Ground',
      studySite: {
        city: 'San Diego',
        state: 'California',
        country: 'USA',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 34.216498,
      longitude: -133.300598,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1513243537,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '123XXSNJG0MQASDF4QFFFFD6Y3',
      publisherName: {
        lastName: 'Leesa',
        firstName: 'Keem',
      },
      callTypeName: 'Fish Call',
      groundType: 'Baja Ground',
      studySite: {
        city: 'Los Angeles',
        state: 'California',
        country: 'USA',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Cprobe',
      sampleRate: 8000,
      latitude: 38.016498,
      longitude: -120.400598,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1496542237,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
];

function main() {
  index.hwscDocumentSvc
    .createDocument(items[0], callback);
}

main();
