const index = require('../index.js');

function callback(err, response) {
  if (err) {
    console.log(err);
  } else {
    console.log('Response ', response);
    // console.log('Length ', response.fileMetadataCollection.length)
  }
}

const items = [
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Conga',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 21.37382047121921,
      longitude: -109.9239326211374,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1394709793,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Gunshot Maybe',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 8000,
      latitude: 19.458841946577305,
      longitude: -112.5826240273874,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1393816993,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Squeak Ascending Shriek',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 27.240461771986347,
      longitude: -118.2955146523874,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1393816993,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Squelch',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 21.593280323417385,
      longitude: -123.03730859289931,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1392026713,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Unknown 13',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 8000,
      latitude: 30.269698300765437,
      longitude: -120.68623437414931,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1427207773,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Whup Ascending Shriek',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Bprobe',
      sampleRate: 8000,
      latitude: 15.74348878054948,
      longitude: -107.24676851430542,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1394115793,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0000XSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Seger',
        firstName: 'Kerri',
      },
      callTypeName: 'Wookie',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Cabo Mexico',
        country: 'Mexico',
      },
      ocean: 'Pacific Ocean',
      sensorType: 'Tag',
      sensorName: 'Acousonde',
      sampleRate: 8000,
      latitude: 24.103832712055066,
      longitude: -92.64963900883936,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1392031993,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Feed',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Norfolk',
        state: 'VA',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Probe',
      sensorName: 'SonarTech',
      sampleRate: 18000,
      latitude: 33.645088,
      longitude: -64.234964,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1457868193,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
      'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },
  {
    data: {
      duid: '',
      uuid: '0XXXXSNJG0MQJHBF4QX1EFD6Y3',
      publisherName: {
        lastName: 'Faraon',
        firstName: 'Conard',
      },
      callTypeName: 'Part Migration',
      groundType: 'Breeding Migrating',
      studySite: {
        city: 'Providence',
        state: 'Maine',
        country: 'USA',
      },
      ocean: 'Atlantic Ocean',
      sensorType: 'Probe',
      sensorName: 'SonarTech',
      sampleRate: 18000,
      latitude: 39.836641,
      longitude: -55.094339,
      imageUrlsMap: {},
      audioUrlsMap: {},
      videoUrlsMap: {},
      fileUrlsMap: {},
      recordTimestamp: 1457004193,
      createTimestamp: 0,
      updateTimestamp: 0,
      isPublic: true,
    },
    imageUrls: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
    audioUrls: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
    videoUrls: [],
    fileUrls: [],
  },


//   {
//     pi: 'Kim',
//     firstName: 'Lisa',
//     callTypeName: 'Chilly',
//     regionCountry: 'McMurdoAntartica',
//     region: 'Southern Ocean',
//     sensorType: 'Pill',
//     sensorName: 'Mead',
//     date: 20130210,
//     time: 113355,
//     samplingRate: 600,
//     quality: 3,
//     groundType: 'HibernateMigrating',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: -60.460843,
//     long: -0.602151
//   },
//   {
//     pi: 'Claus',
//     firstName: 'Santa',
//     callTypeName: 'Holiday',
//     regionCountry: 'NorthPole',
//     region: 'Arctic Ocean',
//     sensorType: 'Pen',
//     sensorName: 'List',
//     date: 20170306,
//     time: 142331,
//     samplingRate: 10000,
//     quality: 5,
//     groundType: 'HolidayMigrating',
//     image_url: [],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 71.173307,
//     long: -12.864505
//   },
//   {
//     pi: 'Ghadimi',
//     firstName: 'Pouria',
//     callTypeName: 'Uber',
//     regionCountry: 'PersianGulf',
//     region: 'Indian Ocean',
//     sensorType: 'Phone',
//     sensorName: 'Apple',
//     date: 20150324,
//     time: 142637,
//     samplingRate: 18000,
//     quality: 3,
//     groundType: 'UberMigrating',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 3.819570,
//     long: 69.752682
//   },

//
// var more = [{
//   pi: 'Abadi',
//   firstName: 'Shima',
//   callTypeName: 'Oishi',
//   regionCountry: 'TokyoJapan',
//   region: 'Pacific Ocean',
//   sensorType: 'Satellite',
//   sensorName: 'Toyota',
//   date: 20160201,
//   time: 182313,
//   samplingRate: 4000,
//   quality: 2,
//   groundType: 'SocialMigrating',
//   image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
//     'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
//   audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
//   video_url: [],
//   file_url: [],
//   lat: 28.811156,
//   long: 162.170557
// },
//   {
//     pi: 'Abadi',
//     firstName: 'Shima',
//     callTypeName: 'Emitter',
//     regionCountry: 'SeoulS.Korea',
//     region: 'Pacific Ocean',
//     sensorType: 'Inject',
//     sensorName: 'Samsung',
//     date: 20180307,
//     time: 180640,
//     samplingRate: 2000,
//     quality: 4,
//     groundType: 'EventEmitter',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 48.839540,
//     long: 164.983057
//   },
//   {
//     pi: 'Doe',
//     firstName: 'John',
//     callTypeName: 'AlaMoana',
//     regionCountry: 'WaikikiHawaii',
//     region: 'Pacific Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20180110,
//     time: 131123,
//     samplingRate: 18000,
//     quality: 5,
//     groundType: 'HeatGround',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 34.136708,
//     long: -156.153452
//   },
//   {
//     pi: 'Doe',
//     firstName: 'John',
//     callTypeName: 'Freeze',
//     regionCountry: 'NorthPole',
//     region: 'Arctic Ocean',
//     sensorType: 'Stick',
//     sensorName: 'Northrup',
//     date: 20171110,
//     time: 105232,
//     samplingRate: 8000,
//     quality: 4,
//     groundType: 'ColdGround',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 80.871617,
//     long: -132.531781
//   },
//   {
//     pi: 'Doe',
//     firstName: 'Jane',
//     callTypeName: 'Unknown21',
//     regionCountry: 'NorthPole',
//     region: 'Arctic Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Bprobe',
//     date: 20170324,
//     time: 202637,
//     samplingRate: 12000,
//     quality: 5,
//     groundType: 'ColdGround',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
//       'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 82.852433,
//     long: 13.718219
//   },
//   {
//     pi: 'Flintstones',
//     firstName: 'Fred',
//     callTypeName: 'FishingTrip',
//     regionCountry: 'McMurdoAntartica',
//     region: 'Southern Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20160306,
//     time: 222331,
//     samplingRate: 18000,
//     quality: 2,
//     groundType: 'FreezeField',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: -58.179671,
//     long: 51.716274
//   },
//   {
//     pi: 'Flintstones',
//     firstName: 'Wilma',
//     callTypeName: 'FishingTrip',
//     regionCountry: 'McMurdoAntartica',
//     region: 'Southern Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20160210,
//     time: 113355,
//     samplingRate: 7000,
//     quality: 3,
//     groundType: 'FreezeField',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: -58.179671,
//     long: 141.013149
//   }];
//
// var last = [{
//   pi: 'Tsukino',
//   firstName: 'Serena',
//   callTypeName: 'Sailor',
//   regionCountry: 'AtlantaGeorgia',
//   region: 'Atlantic Ocean',
//   sensorType: 'Satellite',
//   sensorName: 'Toyota',
//   date: 20180201,
//   time: 182313,
//   samplingRate: 4000,
//   quality: 7,
//   groundType: 'Accent',
//   image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
//     'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
//   audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
//   video_url: [],
//   file_url: [],
//   lat: 31.188857,
//   long: -71.682163
// },
//   {
//     pi: 'Tsukino',
//     firstName: 'Serana',
//     callTypeName: 'Event',
//     regionCountry: 'AtlantaGeorgia',
//     region: 'Atlantic Ocean',
//     sensorType: 'Inject',
//     sensorName: 'Samsung',
//     date: 20180307,
//     time: 180640,
//     samplingRate: 21000,
//     quality: 4,
//     groundType: 'Database',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 32.136476,
//     long: -72.266717
//   },
//   {
//     pi: 'Rizal',
//     firstName: 'Jose',
//     callTypeName: 'Dependency',
//     regionCountry: 'MiamiFlorida',
//     region: 'Atlantic Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20140410,
//     time: 131123,
//     samplingRate: 25000,
//     quality: 5,
//     groundType: 'Mongo',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 33.025174,
//     long: -67.256952
//   },
//   {
//     pi: 'Rizal',
//     firstName: 'Jose',
//     callTypeName: 'Injection',
//     regionCountry: 'MiamiFlorida',
//     region: 'Atlantic Ocean',
//     sensorType: 'Stick',
//     sensorName: 'Northrup',
//     date: 20131210,
//     time: 105232,
//     samplingRate: 9000,
//     quality: 4,
//     groundType: 'Node',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 30.257095,
//     long: -72.442499
//   },
//   {
//     pi: 'Jackson',
//     firstName: 'Michael',
//     callTypeName: 'Component',
//     regionCountry: 'KeralaIndia',
//     region: 'Indian Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Bprobe',
//     date: 20121124,
//     time: 202637,
//     samplingRate: 3000,
//     quality: 5,
//     groundType: 'CSharp',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
//       'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 1.374764,
//     long: 66.188233
//   },
//   {
//     pi: 'Jackson',
//     firstName: 'Michael',
//     callTypeName: 'Vue',
//     regionCountry: 'KeralaIndia',
//     region: 'Indian Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20130206,
//     time: 232331,
//     samplingRate: 2000,
//     quality: 2,
//     groundType: 'C++',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_WhupAscendingShriek_CaboMexico_Tag_Acousonde_20140306_142331_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: -6.346461,
//     long: 74.362061
//   },
//   {
//     pi: 'Phelps',
//     firstName: 'Michael',
//     callTypeName: 'Angular',
//     regionCountry: 'NorfolkVirginia',
//     region: 'Atlantic Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20160210,
//     time: 233355,
//     samplingRate: 1000,
//     quality: 3,
//     groundType: 'Java',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 35.755160,
//     long: -64.307162
//   },
//   {
//     pi: 'Phelps',
//     firstName: 'Michael',
//     callTypeName: 'React',
//     regionCountry: 'KeralaIndia',
//     region: 'Indian Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20170210,
//     time: 103355,
//     samplingRate: 17000,
//     quality: 3,
//     groundType: 'Spice',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Wookie_CaboMexico_Tag_Acousonde_20140210_113355_800_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: -3.193761,
//     long: 57.662842
//   }];
//
// var lastone = [{
//   pi: 'Fisher',
//   firstName: 'Wesley',
//   callTypeName: 'Carne',
//   regionCountry: 'BajaMexico',
//   region: 'Pacific Ocean',
//   sensorType: 'Tag',
//   sensorName: 'Acousonde',
//   date: 20180313,
//   time: 112313,
//   samplingRate: 8000,
//   quality: 3,
//   groundType: 'BreedingMigrating',
//   image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.jpg',
//     'https://hwscdevstorage.blob.core.windows.net/images/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.png'],
//   audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Conga_CaboMexico_Tag_Acousonde_20140313_112313_8000_3_BreedingMigrating.wav'],
//   video_url: [],
//   file_url: [],
//   lat: 20.314578,
//   long: -122.916174
// },
//   {
//     pi: 'Fisher',
//     firstName: 'Wesley',
//     callTypeName: 'Asada',
//     regionCountry: 'BajaMexico',
//     region: 'Pacific Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Bprobe',
//     date: 20180307,
//     time: 130640,
//     samplingRate: 8000,
//     quality: 3,
//     groundType: 'BreedingMigrating',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_GunshotMaybe_CaboMexico_Tag_Bprobe_20140307_130640_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 28.469495,
//     long: -129.947424
//   },
//   {
//     pi: 'White',
//     firstName: 'Charles',
//     callTypeName: 'FishTaco',
//     regionCountry: 'SanDiegoCalifornia',
//     region: 'Pacific Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20180210,
//     time: 193123,
//     samplingRate: 8000,
//     quality: 2,
//     groundType: 'BreedingMigrating',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_SqueakAscendingShriek_CaboMexico_Tag_Acousonde_20140210_093123_8000_2_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 37.996406,
//     long: -139.365051
//   },
//   {
//     pi: 'White',
//     firstName: 'Charles',
//     callTypeName: 'Guacamole',
//     regionCountry: 'SanDiegoCalifornia',
//     region: 'Pacific Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Acousonde',
//     date: 20180210,
//     time: ' 105232',
//     samplingRate: 8000,
//     quality: 4,
//     groundType: 'BreedingMigrating',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.jpg'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Squelch_CaboMexico_Tag_Acousonde_20140210_ 105232_8000_4_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 37.509971,
//     long: -152.197083
//   },
//   {
//     pi: 'Foote',
//     firstName: 'Bobby',
//     callTypeName: 'SalsaVerde',
//     regionCountry: 'LosAngelesCalifornia',
//     region: 'Pacific Ocean',
//     sensorType: 'Tag',
//     sensorName: 'Bprobe',
//     date: 20180324,
//     time: 142637,
//     samplingRate: 8000,
//     quality: 3,
//     groundType: 'BreedingMigrating',
//     image_url: ['https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.jpg',
//       'https://hwscdevstorage.blob.core.windows.net/images/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.png'],
//     audio_url: ['https://hwscdevstorage.blob.core.windows.net/audios/Seger_Unknown13_CaboMexico_Tag_Bprobe_20150324_142637_8000_3_BreedingMigrating.wav'],
//     video_url: [],
//     file_url: [],
//     lat: 34.016498,
//     long: -133.300598
//   }
];

function main() {
  index.hwscDocumentSvc
    .createDocument(items[0], callback);
}

main();
