// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document.proto

package hwscDocumentSvcPb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileType int32

const (
	FileType_FILE  FileType = 0
	FileType_AUDIO FileType = 1
	FileType_IMAGE FileType = 2
	FileType_VIDEO FileType = 3
)

var FileType_name = map[int32]string{
	0: "FILE",
	1: "AUDIO",
	2: "IMAGE",
	3: "VIDEO",
}

var FileType_value = map[string]int32{
	"FILE":  0,
	"AUDIO": 1,
	"IMAGE": 2,
	"VIDEO": 3,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{0}
}

type Publisher struct {
	// @inject_tag: bson:"lastName"
	LastName string `protobuf:"bytes,1,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty" bson:"lastName"`
	// @inject_tag: bson:"firstName"
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty" bson:"firstName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Publisher) Reset()         { *m = Publisher{} }
func (m *Publisher) String() string { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()    {}
func (*Publisher) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{0}
}

func (m *Publisher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publisher.Unmarshal(m, b)
}
func (m *Publisher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publisher.Marshal(b, m, deterministic)
}
func (m *Publisher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publisher.Merge(m, src)
}
func (m *Publisher) XXX_Size() int {
	return xxx_messageInfo_Publisher.Size(m)
}
func (m *Publisher) XXX_DiscardUnknown() {
	xxx_messageInfo_Publisher.DiscardUnknown(m)
}

var xxx_messageInfo_Publisher proto.InternalMessageInfo

func (m *Publisher) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Publisher) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type StudySite struct {
	// @inject_tag: bson:"city"
	City string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty" bson:"city"`
	// @inject_tag: bson:"state"
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty" bson:"state"`
	// @inject_tag: bson:"province"
	Province string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty" bson:"province"`
	// @inject_tag: bson:"country"
	Country              string   `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty" bson:"country"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *StudySite) Reset()         { *m = StudySite{} }
func (m *StudySite) String() string { return proto.CompactTextString(m) }
func (*StudySite) ProtoMessage()    {}
func (*StudySite) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{1}
}

func (m *StudySite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudySite.Unmarshal(m, b)
}
func (m *StudySite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudySite.Marshal(b, m, deterministic)
}
func (m *StudySite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudySite.Merge(m, src)
}
func (m *StudySite) XXX_Size() int {
	return xxx_messageInfo_StudySite.Size(m)
}
func (m *StudySite) XXX_DiscardUnknown() {
	xxx_messageInfo_StudySite.DiscardUnknown(m)
}

var xxx_messageInfo_StudySite proto.InternalMessageInfo

func (m *StudySite) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *StudySite) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StudySite) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *StudySite) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

// Request for AddFileMetadata & DeleteFileMetadata
type FileMetadataTransaction struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Fuid                 string   `protobuf:"bytes,2,opt,name=fuid,proto3" json:"fuid,omitempty"`
	Duid                 string   `protobuf:"bytes,3,opt,name=duid,proto3" json:"duid,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Media                FileType `protobuf:"varint,5,opt,name=media,proto3,enum=hwsc.FileType" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FileMetadataTransaction) Reset()         { *m = FileMetadataTransaction{} }
func (m *FileMetadataTransaction) String() string { return proto.CompactTextString(m) }
func (*FileMetadataTransaction) ProtoMessage()    {}
func (*FileMetadataTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{2}
}

func (m *FileMetadataTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMetadataTransaction.Unmarshal(m, b)
}
func (m *FileMetadataTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMetadataTransaction.Marshal(b, m, deterministic)
}
func (m *FileMetadataTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMetadataTransaction.Merge(m, src)
}
func (m *FileMetadataTransaction) XXX_Size() int {
	return xxx_messageInfo_FileMetadataTransaction.Size(m)
}
func (m *FileMetadataTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMetadataTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_FileMetadataTransaction proto.InternalMessageInfo

func (m *FileMetadataTransaction) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FileMetadataTransaction) GetFuid() string {
	if m != nil {
		return m.Fuid
	}
	return ""
}

func (m *FileMetadataTransaction) GetDuid() string {
	if m != nil {
		return m.Duid
	}
	return ""
}

func (m *FileMetadataTransaction) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *FileMetadataTransaction) GetMedia() FileType {
	if m != nil {
		return m.Media
	}
	return FileType_FILE
}

// Response for ListDistinctFieldValues
// Request for QueryDocument
type QueryTransaction struct {
	// @inject_tag: bson:"publishers"
	Publishers []*Publisher `protobuf:"bytes,1,rep,name=publishers,proto3" json:"publishers,omitempty" bson:"publishers"`
	// @inject_tag: bson:"studySites"
	StudySites []*StudySite `protobuf:"bytes,2,rep,name=study_sites,json=studySites,proto3" json:"study_sites,omitempty" bson:"studySites"`
	// @inject_tag: bson:"callTypes"
	CallTypes []string `protobuf:"bytes,3,rep,name=call_types,json=callTypes,proto3" json:"call_types,omitempty" bson:"callTypes"`
	// @inject_tag: bson:"groundTypes"
	GroundTypes []string `protobuf:"bytes,4,rep,name=ground_types,json=groundTypes,proto3" json:"ground_types,omitempty" bson:"groundTypes"`
	// @inject_tag: bson:"sensorTypes"
	SensorTypes []string `protobuf:"bytes,5,rep,name=sensor_types,json=sensorTypes,proto3" json:"sensor_types,omitempty" bson:"sensorTypes"`
	// @inject_tag: bson:"sensorNames"
	SensorNames []string `protobuf:"bytes,6,rep,name=sensor_names,json=sensorNames,proto3" json:"sensor_names,omitempty" bson:"sensorNames"`
	// @inject_tag: bson:"minRecordTimestamp"
	MinRecordTimestamp int64 `protobuf:"varint,7,opt,name=min_record_timestamp,json=minRecordTimestamp,proto3" json:"min_record_timestamp,omitempty" bson:"minRecordTimestamp"`
	// @inject_tag: bson:"maxRecordTimestamp"
	MaxRecordTimestamp   int64    `protobuf:"varint,8,opt,name=max_record_timestamp,json=maxRecordTimestamp,proto3" json:"max_record_timestamp,omitempty" bson:"maxRecordTimestamp"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *QueryTransaction) Reset()         { *m = QueryTransaction{} }
func (m *QueryTransaction) String() string { return proto.CompactTextString(m) }
func (*QueryTransaction) ProtoMessage()    {}
func (*QueryTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{3}
}

func (m *QueryTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTransaction.Unmarshal(m, b)
}
func (m *QueryTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTransaction.Marshal(b, m, deterministic)
}
func (m *QueryTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTransaction.Merge(m, src)
}
func (m *QueryTransaction) XXX_Size() int {
	return xxx_messageInfo_QueryTransaction.Size(m)
}
func (m *QueryTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTransaction proto.InternalMessageInfo

func (m *QueryTransaction) GetPublishers() []*Publisher {
	if m != nil {
		return m.Publishers
	}
	return nil
}

func (m *QueryTransaction) GetStudySites() []*StudySite {
	if m != nil {
		return m.StudySites
	}
	return nil
}

func (m *QueryTransaction) GetCallTypes() []string {
	if m != nil {
		return m.CallTypes
	}
	return nil
}

func (m *QueryTransaction) GetGroundTypes() []string {
	if m != nil {
		return m.GroundTypes
	}
	return nil
}

func (m *QueryTransaction) GetSensorTypes() []string {
	if m != nil {
		return m.SensorTypes
	}
	return nil
}

func (m *QueryTransaction) GetSensorNames() []string {
	if m != nil {
		return m.SensorNames
	}
	return nil
}

func (m *QueryTransaction) GetMinRecordTimestamp() int64 {
	if m != nil {
		return m.MinRecordTimestamp
	}
	return 0
}

func (m *QueryTransaction) GetMaxRecordTimestamp() int64 {
	if m != nil {
		return m.MaxRecordTimestamp
	}
	return 0
}

type Document struct {
	// @inject_tag: bson:"duid"
	Duid string `protobuf:"bytes,1,opt,name=duid,proto3" json:"duid,omitempty" bson:"duid"`
	// @inject_tag: bson:"uuid"
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty" bson:"uuid"`
	// @inject_tag: bson:"publisherName"
	PublisherName *Publisher `protobuf:"bytes,3,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty" bson:"publisherName"`
	// @inject_tag: bson:"callTypeName"
	CallTypeName string `protobuf:"bytes,4,opt,name=call_type_name,json=callTypeName,proto3" json:"call_type_name,omitempty" bson:"callTypeName"`
	// @inject_tag: bson:"groundType"
	GroundType string `protobuf:"bytes,5,opt,name=ground_type,json=groundType,proto3" json:"ground_type,omitempty" bson:"groundType"`
	// @inject_tag: bson:"studySite"
	StudySite *StudySite `protobuf:"bytes,6,opt,name=study_site,json=studySite,proto3" json:"study_site,omitempty" bson:"studySite"`
	// @inject_tag: bson:"ocean"
	Ocean string `protobuf:"bytes,7,opt,name=ocean,proto3" json:"ocean,omitempty" bson:"ocean"`
	// @inject_tag: bson:"sensorType"
	SensorType string `protobuf:"bytes,8,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty" bson:"sensorType"`
	// @inject_tag: bson:"sensorName"
	SensorName string `protobuf:"bytes,9,opt,name=sensor_name,json=sensorName,proto3" json:"sensor_name,omitempty" bson:"sensorName"`
	// @inject_tag: bson:"samplingRate"
	SamplingRate uint32 `protobuf:"varint,10,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty" bson:"samplingRate"`
	// @inject_tag: bson:"latitude"
	Latitude float32 `protobuf:"fixed32,11,opt,name=latitude,proto3" json:"latitude,omitempty" bson:"latitude"`
	// @inject_tag: bson:"longitude"
	Longitude float32 `protobuf:"fixed32,12,opt,name=longitude,proto3" json:"longitude,omitempty" bson:"longitude"`
	// @inject_tag: bson:"imageUrlsMap"
	ImageUrlsMap map[string]string `protobuf:"bytes,13,rep,name=image_urls_map,json=imageUrlsMap,proto3" json:"image_urls_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"imageUrlsMap"`
	// @inject_tag: bson:"audioUrlsMap"
	AudioUrlsMap map[string]string `protobuf:"bytes,14,rep,name=audio_urls_map,json=audioUrlsMap,proto3" json:"audio_urls_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"audioUrlsMap"`
	// @inject_tag: bson:"videoUrlsMap"
	VideoUrlsMap map[string]string `protobuf:"bytes,15,rep,name=video_urls_map,json=videoUrlsMap,proto3" json:"video_urls_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"videoUrlsMap"`
	// @inject_tag: bson:"fileUrlsMap"
	FileUrlsMap map[string]string `protobuf:"bytes,16,rep,name=file_urls_map,json=fileUrlsMap,proto3" json:"file_urls_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"fileUrlsMap"`
	// @inject_tag: bson:"recordTimestamp"
	RecordTimestamp int64 `protobuf:"varint,17,opt,name=record_timestamp,json=recordTimestamp,proto3" json:"record_timestamp,omitempty" bson:"recordTimestamp"`
	// @inject_tag: bson:"createTimestamp"
	CreateTimestamp int64 `protobuf:"varint,18,opt,name=create_timestamp,json=createTimestamp,proto3" json:"create_timestamp,omitempty" bson:"createTimestamp"`
	// @inject_tag: bson:"updateTimestamp"
	UpdateTimestamp int64 `protobuf:"varint,19,opt,name=update_timestamp,json=updateTimestamp,proto3" json:"update_timestamp,omitempty" bson:"updateTimestamp"`
	// @inject_tag: bson:"isPublic"
	IsPublic             bool     `protobuf:"varint,20,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty" bson:"isPublic"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d2790a4091b3173, []int{4}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetDuid() string {
	if m != nil {
		return m.Duid
	}
	return ""
}

func (m *Document) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Document) GetPublisherName() *Publisher {
	if m != nil {
		return m.PublisherName
	}
	return nil
}

func (m *Document) GetCallTypeName() string {
	if m != nil {
		return m.CallTypeName
	}
	return ""
}

func (m *Document) GetGroundType() string {
	if m != nil {
		return m.GroundType
	}
	return ""
}

func (m *Document) GetStudySite() *StudySite {
	if m != nil {
		return m.StudySite
	}
	return nil
}

func (m *Document) GetOcean() string {
	if m != nil {
		return m.Ocean
	}
	return ""
}

func (m *Document) GetSensorType() string {
	if m != nil {
		return m.SensorType
	}
	return ""
}

func (m *Document) GetSensorName() string {
	if m != nil {
		return m.SensorName
	}
	return ""
}

func (m *Document) GetSamplingRate() uint32 {
	if m != nil {
		return m.SamplingRate
	}
	return 0
}

func (m *Document) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Document) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Document) GetImageUrlsMap() map[string]string {
	if m != nil {
		return m.ImageUrlsMap
	}
	return nil
}

func (m *Document) GetAudioUrlsMap() map[string]string {
	if m != nil {
		return m.AudioUrlsMap
	}
	return nil
}

func (m *Document) GetVideoUrlsMap() map[string]string {
	if m != nil {
		return m.VideoUrlsMap
	}
	return nil
}

func (m *Document) GetFileUrlsMap() map[string]string {
	if m != nil {
		return m.FileUrlsMap
	}
	return nil
}

func (m *Document) GetRecordTimestamp() int64 {
	if m != nil {
		return m.RecordTimestamp
	}
	return 0
}

func (m *Document) GetCreateTimestamp() int64 {
	if m != nil {
		return m.CreateTimestamp
	}
	return 0
}

func (m *Document) GetUpdateTimestamp() int64 {
	if m != nil {
		return m.UpdateTimestamp
	}
	return 0
}

func (m *Document) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func init() {
	proto.RegisterEnum("hwsc.FileType", FileType_name, FileType_value)
	proto.RegisterType((*Publisher)(nil), "hwsc.Publisher")
	proto.RegisterType((*StudySite)(nil), "hwsc.StudySite")
	proto.RegisterType((*FileMetadataTransaction)(nil), "hwsc.FileMetadataTransaction")
	proto.RegisterType((*QueryTransaction)(nil), "hwsc.QueryTransaction")
	proto.RegisterType((*Document)(nil), "hwsc.Document")
	proto.RegisterMapType((map[string]string)(nil), "hwsc.Document.AudioUrlsMapEntry")
	proto.RegisterMapType((map[string]string)(nil), "hwsc.Document.FileUrlsMapEntry")
	proto.RegisterMapType((map[string]string)(nil), "hwsc.Document.ImageUrlsMapEntry")
	proto.RegisterMapType((map[string]string)(nil), "hwsc.Document.VideoUrlsMapEntry")
}

func init() { proto.RegisterFile("document.proto", fileDescriptor_9d2790a4091b3173) }

var fileDescriptor_9d2790a4091b3173 = []byte{
	// 806 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4b, 0x8f, 0xdc, 0x44,
	0x10, 0xc6, 0xf3, 0xd8, 0xd8, 0x35, 0x8f, 0x75, 0x9a, 0x95, 0xb0, 0x12, 0x50, 0xcc, 0x90, 0xc3,
	0x84, 0xc3, 0x80, 0x82, 0x40, 0x88, 0x03, 0x68, 0xc5, 0xee, 0x46, 0x23, 0xb1, 0x04, 0x9c, 0x4d,
	0xae, 0x56, 0xc7, 0xee, 0xdd, 0xb4, 0xe2, 0x97, 0xba, 0xdb, 0xc3, 0xce, 0x8f, 0xe0, 0xef, 0x71,
	0xe7, 0x9f, 0x44, 0xd5, 0xed, 0x47, 0xcf, 0xe3, 0xb2, 0xb7, 0xea, 0xaf, 0xbe, 0xfa, 0xaa, 0xa7,
	0xbe, 0x72, 0x0f, 0xcc, 0xd3, 0x32, 0xa9, 0x73, 0x56, 0xa8, 0x55, 0x25, 0x4a, 0x55, 0x92, 0xd1,
	0x87, 0x7f, 0x64, 0xb2, 0x78, 0x05, 0xde, 0x5f, 0xf5, 0xfb, 0x8c, 0xcb, 0x0f, 0x4c, 0x90, 0xa7,
	0xe0, 0x65, 0x54, 0xaa, 0xb8, 0xa0, 0x39, 0x0b, 0x9c, 0xd0, 0x59, 0x7a, 0x91, 0x8b, 0xc0, 0x9f,
	0x34, 0x67, 0xe4, 0x2b, 0x80, 0x5b, 0x2e, 0xda, 0xec, 0x40, 0x67, 0x3d, 0x8d, 0x60, 0x7a, 0xf1,
	0x11, 0xbc, 0x37, 0xaa, 0x4e, 0xb7, 0x6f, 0xb8, 0x62, 0x84, 0xc0, 0x28, 0xe1, 0x6a, 0xdb, 0x68,
	0xe8, 0x98, 0x9c, 0xc1, 0x58, 0x2a, 0xaa, 0xda, 0x52, 0x73, 0x20, 0x4f, 0xc0, 0xad, 0x44, 0xb9,
	0xe1, 0x45, 0xc2, 0x82, 0xa1, 0xe9, 0xd8, 0x9e, 0x49, 0x00, 0x8f, 0x92, 0xb2, 0x2e, 0x94, 0xd8,
	0x06, 0x23, 0x9d, 0x6a, 0x8f, 0x8b, 0x7f, 0x1d, 0xf8, 0xe2, 0x8a, 0x67, 0xec, 0x9a, 0x29, 0x9a,
	0x52, 0x45, 0x6f, 0x04, 0x2d, 0x24, 0x4d, 0x14, 0x2f, 0x0b, 0xe2, 0xc3, 0xb0, 0x16, 0x59, 0xd3,
	0x1a, 0x43, 0xbc, 0xcd, 0x6d, 0xcd, 0xd3, 0xa6, 0xb1, 0x8e, 0x11, 0x4b, 0x11, 0x33, 0x3d, 0x75,
	0x8c, 0x58, 0x8d, 0x98, 0x69, 0xa6, 0x63, 0xf2, 0x1c, 0xc6, 0x39, 0x4b, 0x39, 0x0d, 0xc6, 0xa1,
	0xb3, 0x9c, 0xbf, 0x9c, 0xaf, 0x70, 0x6a, 0x2b, 0xec, 0x7d, 0xb3, 0xad, 0x58, 0x64, 0x92, 0x8b,
	0xff, 0x07, 0xe0, 0xff, 0x5d, 0x33, 0xb1, 0xb5, 0x2f, 0xf2, 0x1d, 0x40, 0xd5, 0x8e, 0x56, 0x06,
	0x4e, 0x38, 0x5c, 0x4e, 0x5e, 0x9e, 0x9a, 0xfa, 0x6e, 0xe4, 0x91, 0x45, 0x21, 0xdf, 0xc3, 0x44,
	0xe2, 0x08, 0x63, 0xc9, 0x15, 0x93, 0xc1, 0xc0, 0xae, 0xe8, 0x66, 0x1b, 0x81, 0x6c, 0x43, 0x89,
	0x9e, 0x24, 0x34, 0xcb, 0x62, 0xb5, 0xad, 0x98, 0x0c, 0x86, 0xe1, 0x10, 0x3d, 0x41, 0x04, 0x2f,
	0x27, 0xc9, 0xd7, 0x30, 0xbd, 0x13, 0x65, 0x5d, 0xa4, 0x0d, 0x61, 0xa4, 0x09, 0x13, 0x83, 0x75,
	0x14, 0xc9, 0x0a, 0x59, 0x8a, 0x86, 0x32, 0x36, 0x14, 0x83, 0xed, 0x53, 0xd0, 0x79, 0x19, 0x9c,
	0xd8, 0x14, 0xf4, 0x1e, 0x6f, 0x7e, 0x96, 0xf3, 0x22, 0x16, 0x2c, 0x29, 0x45, 0x1a, 0x2b, 0x9e,
	0x33, 0xa9, 0x68, 0x5e, 0x05, 0x8f, 0x42, 0x67, 0x39, 0x8c, 0x48, 0xce, 0x8b, 0x48, 0xa7, 0x6e,
	0xda, 0x8c, 0xae, 0xa0, 0xf7, 0x87, 0x15, 0x6e, 0x53, 0x41, 0xef, 0xf7, 0x2a, 0x16, 0xff, 0xb9,
	0xe0, 0x5e, 0x34, 0x2b, 0xdc, 0xd9, 0xe7, 0x1c, 0xb1, 0x6f, 0x60, 0xd9, 0xf7, 0x13, 0xcc, 0xbb,
	0x01, 0x9b, 0xc5, 0x45, 0xc3, 0x8f, 0xf8, 0x30, 0xeb, 0x68, 0x7a, 0xd9, 0x9f, 0xc3, 0xbc, 0x1b,
	0xac, 0xa9, 0x33, 0x4b, 0x31, 0x6d, 0x87, 0xab, 0x59, 0xcf, 0x60, 0x62, 0xcd, 0x57, 0xaf, 0x88,
	0x17, 0x41, 0x3f, 0x5e, 0xb2, 0x02, 0xe8, 0x1d, 0x0d, 0x4e, 0xec, 0xd6, 0xbd, 0xa1, 0x5e, 0x67,
	0x28, 0x7e, 0x23, 0x65, 0xc2, 0x68, 0xa1, 0x07, 0xe7, 0x45, 0xe6, 0x80, 0x6d, 0x2c, 0x8f, 0xf4,
	0x88, 0xbc, 0x08, 0x7a, 0x8b, 0x2c, 0x82, 0xbe, 0xaa, 0x67, 0x13, 0xf4, 0x45, 0xbf, 0x81, 0x99,
	0xa4, 0x79, 0x95, 0xf1, 0xe2, 0x2e, 0x16, 0xf8, 0x0d, 0x42, 0xe8, 0x2c, 0x67, 0xd1, 0xb4, 0x05,
	0xa3, 0xe6, 0x53, 0xcc, 0xa8, 0xe2, 0xaa, 0x4e, 0x59, 0x30, 0x09, 0x9d, 0xe5, 0x20, 0xea, 0xce,
	0xe4, 0x4b, 0xf0, 0xb2, 0xb2, 0xb8, 0x33, 0xc9, 0xa9, 0x4e, 0xf6, 0x00, 0xb9, 0x82, 0x39, 0xcf,
	0xe9, 0x1d, 0x8b, 0x6b, 0x91, 0xc9, 0x38, 0xa7, 0x55, 0x30, 0xd3, 0xbb, 0x1b, 0x9a, 0x9f, 0xda,
	0xba, 0xb6, 0x5a, 0x23, 0xe9, 0xad, 0xc8, 0xe4, 0x35, 0xad, 0x2e, 0xf1, 0x43, 0x8e, 0xa6, 0xdc,
	0x82, 0x50, 0x87, 0xd6, 0x29, 0x2f, 0x7b, 0x9d, 0xf9, 0x51, 0x9d, 0x73, 0x24, 0xed, 0xea, 0x50,
	0x0b, 0x42, 0x9d, 0x0d, 0x4f, 0x99, 0xa5, 0x73, 0x7a, 0x54, 0xe7, 0x1d, 0x92, 0x76, 0x75, 0x36,
	0x16, 0x44, 0x7e, 0x87, 0xd9, 0x2d, 0xcf, 0xac, 0x9f, 0xe5, 0x6b, 0x99, 0x67, 0x7b, 0x32, 0xf8,
	0x1a, 0xec, 0xa8, 0x4c, 0x6e, 0x7b, 0x84, 0xbc, 0x00, 0xff, 0x60, 0xcb, 0x1f, 0xeb, 0x2d, 0x3f,
	0x15, 0x7b, 0x1f, 0xc5, 0x0b, 0xf0, 0x13, 0xc1, 0xa8, 0x62, 0x16, 0x95, 0x18, 0xaa, 0xc1, 0x77,
	0xa8, 0x75, 0x95, 0xee, 0x52, 0x3f, 0x37, 0x54, 0x83, 0xf7, 0xd4, 0xa7, 0xe0, 0x71, 0x19, 0xeb,
	0xfd, 0x4e, 0x82, 0xb3, 0xd0, 0x59, 0xba, 0x91, 0xcb, 0xa5, 0x5e, 0xfd, 0xe4, 0xc9, 0x6f, 0xf0,
	0xf8, 0xc0, 0x15, 0x7c, 0x42, 0x3f, 0xb2, 0xf6, 0xf5, 0xc6, 0x10, 0x17, 0x73, 0x43, 0xb3, 0xba,
	0x7b, 0xbc, 0xf5, 0xe1, 0x97, 0xc1, 0xcf, 0x0e, 0x0a, 0x1c, 0xd8, 0xf1, 0x50, 0x81, 0x03, 0x1f,
	0x1e, 0x24, 0xf0, 0x2b, 0xf8, 0xfb, 0x0e, 0x3c, 0xa4, 0xfe, 0xdb, 0x1f, 0xc1, 0x6d, 0xdf, 0x73,
	0xe2, 0xc2, 0xe8, 0x6a, 0xfd, 0xc7, 0xa5, 0xff, 0x19, 0xf1, 0x60, 0x7c, 0xfe, 0xf6, 0x62, 0xfd,
	0xda, 0x77, 0x30, 0x5c, 0x5f, 0x9f, 0xbf, 0xba, 0xf4, 0x07, 0x18, 0xbe, 0x5b, 0x5f, 0x5c, 0xbe,
	0xf6, 0x87, 0xef, 0x4f, 0xf4, 0xdf, 0xe8, 0x0f, 0x9f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xac, 0x34,
	0x81, 0x13, 0x58, 0x07, 0x00, 0x00,
}
